title: 'Liam EXPOSED'
description: "Uncovering the darkest secrets of a troubled man."
baseurl: "/jekyll-theme-console-demo-dark"
url: "https://liam.exposed"

header_pages:
  - index.md
  - peter.md
  - about.md
  - contact.md

style: dark

footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
